# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude: |
          (?x)^(
              .*\.lock |
              .*\.json
          )$
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.0
    hooks:
      - id: actionlint
  - repo: local
    hooks:
      - id: alex.js
        name: alex.js language checks
        entry: alex
        language: node
        additional_dependencies: ["alex@11.0.1"]
        # note: we ignore the following
        # files as they inherently contain
        # words which are 'false negatives'
        # for alex.js.
        exclude: |
          (?x)^(
              .*\.lock |
              .pre-commit-config.yaml |
              CODE_OF_CONDUCT.md
          )$
