# configuration for repository issues
# see here for more information:
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: Send Microsoft Form entry
    url: https://forms.office.com/r/RLQNXSSk9V
    about: >
      I'd like to send an idea for additions or
      changes without a GitHub account.
